### ISSUE TITLE
Integration with zulip

### ISSUE THREAD

**Issue by derek-austin** [errbotio/errbot#845] opened 2016-09-05 11:47 UTC
Please, consider the integration with [zulip](https://github.com/zulip/zulip/)
(If you know other python based chat server, let me know)

**Comment by zoni** [comment] 2016-09-05 11:54
As with supporting rocket.chat (#627) and mattermost (#390), this would have to come from somebody in the community willing to write and maintain such a backend. Our core contributors currently already have their hands full staying on top of the current backends we support.

We are definitely willing to offer guidance and help to anyone willing to implement and support a zulip backend for errbot though.

**Comment by derAnfaenger** [comment] 2017-08-21 16:35
Hey there! I'm considering to write a backend for Zulip. From looking at some of the existing ones, I have to say that I'm a little overwhelmed by the sheer amount of methods that need to be implemented :) It would be great if you could give me a hint as to which classes / methods require implementation / are optional, so that I can get started with a minimal test implementation.

**Comment by gbin** [comment] 2017-08-22 13:45
Awesome @derAnfaenger, a minimal backend is not that big: I usually start with the person definition and implement the message loop to respond to one to one messages. Then I go into rooms and occupants. From there you can use the backend tester to see if everything is fine for the basic contract. Then you can start to see rendering, mentions, callbacks etc...

**Comment by zoni** [comment] 2017-08-23 16:37
I might also recommend looking at the [telegram backend](https://github.com/errbotio/errbot/blob/master/errbot/backends/telegram_messenger.py).

Because Telegram bots lack support for many of the group functionalities typically found on other networks, the implementation is a lot smaller than most other errbot backends.

**Comment by derAnfaenger** [comment] 2017-08-23 17:19
@gbin @zoni thank you very much for your help! I'll have a look into this the coming days.

**Comment by derAnfaenger** [comment] 2017-10-03 17:05
I have now implemented most of the basic backend stuff. Going for the rest of the room operations and fiels tomorrow. I'm wondering in what form I should submit a PR for this: Would the Zulip plugin reside in an additional repo, or be integrated in the `backends` directory?

**Comment by derAnfaenger** [comment] 2017-10-03 18:48
As a side-note, I think I've noticed some issues with the command handing:
Zulip channel names can contain whitespaces. 

The command  `/room occupants "channel name"`  works and correctly calls `query_room()` with `'channel name'`, but `/room join "channel name"` calls `query_room()` with `'"channel'` - the string encapsulation didn't work.

**Comment by derAnfaenger** [comment] 2017-10-04 13:12
`https://github.com/derAnfaenger/err-backend-zulip/pull/1` adds a Zulip plugin to my personal repo. @derek-austin @zoni @gbin FYI.

**Comment by zoni** [comment] 2017-10-05 15:36
@derAnfaenger nice work!

For the time being, I believe it's best for it to stay in your own repository. Primarily, this will give it some time to mature where you can do rapid releases without being constrained to errbot's own release schedule. It also frees us up from having to do support/maintenance on a backend we can't really support because we aren't using it ourselves and don't have much community support to fall back on.

I do however wish to link it from `README.rst` and http://errbot.io/ so that other people may find it easily. If you could add some installation instructions for users in your own repo, that'd be very helpful. https://github.com/Vaelor/errbot-mattermost-backend may be a good example to take inspiration from. :smile: 

Finally, when I find some free time I'm planning to make our contribution process more transparent. i wish to make it easier for people to help us maintain errbot and to provide better recognition for anyone who does, be it by regularly helping users out, triaging issues, contributing actual code, etc.

(If that is something you'd be interested in on the longer term, let me know and I'll keep you updated on the progress there)

**Comment by zoni** [comment] 2017-10-05 15:40
> As a side-note, I think I've noticed some issues with the command handing

That looks like a (fairly simple) bug in the core [chatroom plugin](https://github.com/errbotio/errbot/blob/7d63b5ecebb72e396fe60d10a5aad993cb991a12/errbot/core_plugins/chatRoom.py), likely caused by a few of the subcommands not using a proper argument parser. Feel free to open a separate issue for this and/or offer a fix for it directly.

**Comment by derAnfaenger** [comment] 2017-10-06 08:19
Cool! I added basic insructions in the README.md on the master branch, should get some feedback on the bot in the next couple days and then merge the plugin. Considering the link from the `README.rst`, I think the plugin will short-term be integrated somehwere the `zulip` repo, will notify you once we have a definite location.

**Comment by derAnfaenger** [comment] 2017-10-26 14:21
@zoni if you want, you can link to the Zulip Errbot integration here: https://github.com/zulip/errbot-backend-zulip

@timabbott FYI

**Comment by gbin** [comment] 2017-10-26 14:29
Thx @derAnfaenger this is actually closing this feature request! :)

**Closed by gbin** 2017-10-26 14:29 UTC
Labels: type: feature

**Comment by timabbott** [comment] 2017-10-26 16:56
@derAnfaenger it seems like there's 2 follow-up tasks herE:
* We should open a pull request to link to the integration in http://errbot.io/en/latest/features.html and the README.md
* We should at least open and maybe fix the chatroom plugin bug discussed above, if we haven't already.

**Comment by zoni** [comment] 2017-10-26 17:48
> We should open a pull request to link to the integration in http://errbot.io/en/latest/features.html and the README.md

Beat you to it. :smile: See https://github.com/errbotio/errbot/commit/66acb9785aaed46114ec8c99ae3ce22a10c936ac.

> We should at least open and maybe fix the chatroom plugin bug discussed above, if we haven't already.

@derAnfaenger filed the issue (https://github.com/errbotio/errbot/issues/1115). Fixing it for us would be even more welcome! :grin:

**Comment by derAnfaenger** [comment] 2017-10-27 11:30
Submitted #1128 for #1115.
