### ISSUE TITLE
Errbot 4.2.2  python 2.7. Error with command errbot.

### ISSUE THREAD

**Issue by locdoan12121997** [errbotio/errbot#1103] opened 2017-09-20 11:00 UTC
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [x ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 4.2.2
* OS version: ubuntu 16.04 lts
* Python version: 2.7
* Using a virtual environment: yes

### Issue description

Please describe your bug/feature/problem here.
The more information you can provide, the better.
I can only use python 2.7. I'm trying to install errbot version 4.2.2. I installed it. I got error running errbot command. Can you help me implement errbot without using python 3

> 17:42:12 DEBUG    errbot.specific_plugin_ma Load the one remaining...
17:42:12 ERROR    yapsy                     Unable to import plugin: /home/thienloc/working/errbot/.venv/local/lib/python2.7/site-packages/errbot/backends/text
Traceback (most recent call last):
  File "/home/thienloc/working/errbot/.venv/local/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/home/thienloc/working/errbot/.venv/local/lib/python2.7/site-packages/errbot/backends/text.py", line 14, in <module>
    from errbot.rendering import ansi, text, xhtml, imtext
  File "/home/thienloc/working/errbot/.venv/local/lib/python2.7/site-packages/errbot/rendering/__init__.py", line 10, in <module>
    MD_ESCAPE_RE = re.compile(u'|'.join(re.escape(c) for c in Markdown.ESCAPED_CHARS))
AttributeError: type object 'Markdown' has no attribute 'ESCAPED_CHARS'
17:42:12 ERROR    errbot.bootstrap          Unable to load or configure the backend.
Traceback (most recent call last):
  File "/home/thienloc/working/errbot/.venv/local/lib/python2.7/site-packages/errbot/bootstrap.py", line 126, in setup_bot
    bot = backendpm.get_plugin_by_name(backend_name)
  File "/home/thienloc/working/errbot/.venv/local/lib/python2.7/site-packages/errbot/specific_plugin_manager.py", line 87, in get_plugin_by_name
    raise Exception(u'Error loading plugin %s:\nError:\n%s\n' % (name, formatted_error))
Exception: Error loading plugin Text:
Error:
<type 'exceptions.AttributeError'>:
  File "/home/thienloc/working/errbot/.venv/local/lib/python2.7/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File "/home/thienloc/working/errbot/.venv/local/lib/python2.7/site-packages/errbot/backends/text.py", line 14, in <module>
    from errbot.rendering import ansi, text, xhtml, imtext
  File "/home/thienloc/working/errbot/.venv/local/lib/python2.7/site-packages/errbot/rendering/__init__.py", line 10, in <module>
    MD_ESCAPE_RE = re.compile(u'|'.join(re.escape(c) for c in Markdown.ESCAPED_CHARS))

### Steps to reproduce
I create a folder, virtual environment.
I downloaded errbot 4.2.2 here: https://pypi.python.org/pypi/errbot/4.2.2
I installed python-telegram-bot
I created a requirements.txt file
I installed it by pip install errbot and I also clicked installation suggestion in pycharm.
When I check errbot --version, it's 4.2.2
Then I click errbot, I got error.

In case of a bug, please describe the steps we need to take in order to reproduce your issue.
If you cannot easily reproduce the issue please let us know and provide as much information as you can which might help us pinpoint the problem.

### Additional info

If you have any more information, please specify it here.

**Comment by sijis** [comment] 2017-10-04 06:20
Do you still need assistance with setting up errbot?

**Comment by sijis** [comment] 2017-10-06 20:40
Ok, I'm able to reproduce this issue. It seems this has been brought up a few times.

Its a duplicate of https://github.com/errbotio/errbot/issues/1088, https://github.com/errbotio/errbot/issues/953

The workaround, while validating this, was to do the following:
`pip install Markdown==2.6.7`

**Comment by zoni** [comment] 2017-10-07 08:16
Closing this as there's a workaround available and this related to an old, no longer maintained version of errbot.

**Closed by zoni** 2017-10-07 08:16 UTC
