### ISSUE TITLE
New markdown version breaking slack backend

### ISSUE THREAD

**Issue by SvenNederhoff** [errbotio/errbot#1088] opened 2017-08-24 08:43 UTC
In order to let us help you better, please fill out the following fields as best you can:

### I am running...

* Errbot version: 9.9.9 (fresh pulled master version)
* OS version: Debian Jessie 
* Python version: Python 3.4.2
* Using a virtual environment: yes

### Issue description

When updating all the requirements the slack backend throws an AttributeErro
```
AttributeError: type object 'Markdown' has no attribute 'ESCAPED_CHARS'
```

after some investigation downgrading Markdown to version 2.6.7 was the quick fix

changed this [`'markdown'`](https://github.com/errbotio/errbot/blob/master/setup.py#L42) to `markdown==2.6.7`

### Steps to reproduce

Update everything and run the bot while using the slack backend

**Comment by gbin** [comment] 2017-08-24 17:43
#953 <- How did this reappeared? Can you check if you are really using head from Errbot? !about in the chat.

**Comment by gbin** [comment] 2017-08-24 17:44
On my prod instance running on slack: Markdown==2.6.8

**Comment by SvenNederhoff** [comment] 2017-08-30 09:40
@gbin 
```
[Bot] RafikiAPP [11:40] 
This is Errbot version 9.9.9
```

``
(virtualenv)errbot@errbot2:/srv/errbot/repository$ git status 
HEAD detached at cded960
```

**Comment by sijis** [comment] 2017-10-07 04:49
I'm wondering if this is a debian related issue.

Using a `fedora:26` container
```
$ dnf install python3 python3-pip
$ pip3 install errbot
$ errbot --init
$ vi config.py
$ errbot -T
$ python3 -V => Python 3.6.2
```

Using a `ubuntu:16.04` container
```
$ apt-get update
$ apt-get install python3 python3-pip
$ pip3 install errbot
$ vi config.py
$ errbot --init
$ python3 -V => Python 3.5.2
```

**Comment by zoni** [comment] 2017-10-07 08:15
I'm unable to reproduce this with errbot HEAD and Markdown 2.6.9.

cded960 predates 374b7ef50d3c5f8a49613fd0732a6c7c736940dd which is from #953 and contained a fix for this issue. It appears you were somehow not running a recent git version, but a much older one which didn't have this fix for this yet.

**Closed by zoni** 2017-10-07 08:15 UTC
