### ISSUE TITLE
Slack backend is broken with python slackclient >= 1.0.5

### ISSUE THREAD

**Issue by vdemonchy** [errbotio/errbot#956] opened 2017-01-31 17:15 UTC
### I am...

* [X] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 4.3.6
* OS version: debian jessie
* Python version: 3.6
* Using a virtual environment: yes

### Issue description

When using the slack backend, errbot cannot send back an answer to commands because it fails with the following error:
```
16:47:35 ERROR    errbot.backends.slack     message event handler raised an exception
Traceback (most recent call last):
  File "/app/venv/lib/python3.6/site-packages/errbot/backends/slack.py", line 417, in _dispatch_slack_message
    event_handler(message)
  File "/app/venv/lib/python3.6/site-packages/errbot/backends/slack.py", line 499, in _message_event_handler
    msg.to = SlackPerson(self.sc, self.username_to_userid(self.sc.server.username),
  File "/app/venv/lib/python3.6/site-packages/errbot/backends/slack.py", line 547, in username_to_userid
    raise UserDoesNotExistError("Cannot find user %s" % name)
errbot.backends.base.UserDoesNotExistError: Cannot find user toto
```

I have digged a bit and it looks like the error comes from the following commit in the python slack client which has been integrated in the version 1.0.5 : https://github.com/slackapi/python-slackclient/commit/4b7f996ed4a6a51bc5d6e54d305a3f933e10380c

Reverting to a prior version of slackclient makes it work again.
I'm currently trying to work on a fix.

### Steps to reproduce

Use the python slackclient at the latest version with the errbot slack backend and try any command, it should fail with error described above.

### Additional info

None

**Comment by zoni** [comment] 2017-02-06 20:26
Closing this as a duplicate of #949. If you could confirm my proposed fix (#961) that'd be great!

**Closed by zoni** 2017-02-06 20:26 UTC
