### ISSUE TITLE
TypeError: String or Integer object expected for key, unicode found

### ISSUE THREAD

**Issue by zahnp4sta** [errbotio/errbot#700] opened 2016-04-02 13:31 UTC
I just installed errbot, but im getting this error on first run:

15:20:39 ERROR    errbot.backends.base      Exception occurred in serve_once:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/errbot/backends/base.py", line 599, in serve_forever
    if self.serve_once():
  File "/usr/lib/python2.7/site-packages/errbot/backends/telegram_messenger.py", line 215, in serve_once
    offset = self[u'_telegram_updates_offset']
  File "/usr/lib/python2.7/site-packages/errbot/storage/__init__.py", line 46, in __getitem__
    return self._store.get(key)
  File "/usr/lib/python2.7/site-packages/errbot/storage/shelf.py", line 18, in get
    return self.shelf[key]
  File "/usr/lib64/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
  File "/usr/lib64/python2.7/bsddb/__init__.py", line 270, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib64/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib64/python2.7/bsddb/__init__.py", line 270, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
TypeError: String or Integer object expected for key, unicode found

Then I found this: https://github.com/errbotio/errbot/issues/232

But I guess the problem is somewhere else.

CentOS 7.2.1511
Python 2.7.5

pip freeze shows:

3to2==1.1.1
ansi==0.1.3
apipkg==1.4
backports.functools-lru-cache==1.2.1
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.4.1
bottle==0.12.9
cffi==1.5.2
colorlog==2.6.1
config==0.3.9
configparser==3.5.0b2
cryptography==1.3.1
daemonize==2.4.6
dnspython==1.12.0
docutils==0.12
enum34==1.1.2
errbot==9.9.9
execnet==1.4.1
flaky==3.1.1
funcsigs==0.4
future==0.15.2
gyp==0.1
idna==2.1
iniparse==0.4
ipaddress==1.0.16
IPy==0.75
javapackages==1.0.0
Jinja2==2.8
lxml==3.2.1
Markdown==2.6.6
MarkupSafe==0.23
mock==1.3.0
nose==1.3.7
pbr==1.8.1
pep8==1.7.0
policycoreutils-default-encoding==0.1
py==1.4.31
pyasn1==0.1.9
pycparser==2.14
pycurl==7.19.0
Pygments==2.1.3
pygments-markdown-lexer==0.1.0.dev39
pygpgme==0.3
pyliblzma==0.5.3
pyOpenSSL==16.0.0
pytest==2.9.1
pytest-xdist==1.14
python-telegram-bot==3.4
pyxattr==0.5.1
requests==2.9.1
rocket-errbot==1.2.5
seobject==0.1
sepolicy==1.1
six==1.10.0
threadpool==1.3.2
typing==3.5.0.1
urlgrabber==3.10
virtualenv==1.10.1
waitress==0.8.10
WebOb==1.6.0
WebTest==2.0.20
Yapsy==1.11.223
yum-metadata-parser==1.1.4

**Comment by zoni** [comment] 2016-04-02 13:35
This is probably a Python-2.7 specific bug (we develop and  test actively with Python 3.x, so subtle bugs tend to slip through on 2.7 from time to time).

I will see if I can reproduce and fix this for you, but until then, perhaps you can use Python 3.x? (if you don't have any specific reason to use 2.7, I strongly suggest using Python 3 anyway :smile:)

**Comment by zahnp4sta** [comment] 2016-04-02 15:19
Alright, seems to work with python 3.4

Thanks!

**Comment by zoni** [comment] 2016-04-02 15:23
I'm going to keep this open because it is an actual issue on Python 2.7 though (I was just able to reproduce it) :smile:

**Comment by zoni** [comment] 2016-04-02 15:36
Fixed in 06cabdeb07b684870d1eb284c239e30f302f6e02.

**Closed by zoni** 2016-04-02 15:36 UTC
Labels: #regression, #Telegram, bug, difficulty: easy, priority: high, type: bug
