### ISSUE TITLE
problem installing errbot on Ubuntu Jammy Jellyfish 22.04 LTS in Oct 2023

### ISSUE THREAD

**Issue by danhimalplanet** [errbotio/errbot#1662] opened 2023-10-19 04:31 UTC
**Describe the bug**
I am unable to run `errbot`

**To Reproduce**
new install of Ubuntu Jammy Jellyfish 22.04 LTS
I create and use a new Python 3.10.12 virtualenv:
```
$ python3 -m venv .venv
$ source .venv/bin/activate
```
I have ubuntu package python3-dev installed. I install the errbot pypi module:
```
$ pip install errbot
```
running errbot gives an error
```
$ errbot
Traceback (most recent call last):
  File "/home/ubuntu/clones/errbot-test/.venv/bin/errbot", line 5, in <module>
    from errbot.cli import main
  File "/home/ubuntu/clones/errbot-test/.venv/lib/python3.10/site-packages/errbot/__init__.py", line 19, in <module>
    from .core_plugins.wsview import WebView, route
  File "/home/ubuntu/clones/errbot-test/.venv/lib/python3.10/site-packages/errbot/core_plugins/__init__.py", line 1, in <module>
    from flask.app import Flask
  File "/home/ubuntu/clones/errbot-test/.venv/lib/python3.10/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/home/ubuntu/clones/errbot-test/.venv/lib/python3.10/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/home/ubuntu/clones/errbot-test/.venv/lib/python3.10/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/home/ubuntu/clones/errbot-test/.venv/lib/python3.10/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/home/ubuntu/clones/errbot-test/.venv/lib/python3.10/site-packages/werkzeug/urls.py)
```
relevant part of the Traceback is probably:
```
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' 
```
**Environment (please complete the following information):**
- Errbot version:  `6.1.9`
- OS version:  `Ubuntu Jammy Jellyfish 22.04 LTS`
- Python version:  `3.10.12`
- Using a virtual environment:  `yes`
- Using Docker: `no`

**Additional context**
output of `pip freeze`
[pip_freeze.txt](https://github.com/errbotio/errbot/files/13037932/pip_freeze.txt)

**Comment by lachiewalker** [comment] 2023-12-18 05:50
`pip uninstall werkzeug` -> `pip install werkzeug==2.2.2`

**Comment by sijis** [comment] 2024-01-26 08:00
Do you have the same behavior with the latest release?

**Comment by sijis** [comment] 2024-01-27 06:47
Closing. Unable to reproduce with latest version.

**Closed by sijis** 2024-01-27 06:47 UTC
Labels: type: bug
