### ISSUE TITLE
Cannot get Errbot to join rooms on Hipchat Server

### ISSUE THREAD

**Issue by sivy** [errbotio/errbot#857] opened 2016-09-30 00:08 UTC
Not sure where to post this, but I cannot get Errbot to join rooms on our internal Hipchat Server. I think it's a release behind the publicly available server, but not sure what version.

```
2016-09-29 17:02:47,140 ERROR    errbot.plugins.ChatRoom   Joining room 'BOT_HOME' failed
Traceback (most recent call last):
  File "/Users/sivy/envs/bot-py3/lib/python3.5/site-packages/errbot/core_plugins/chatRoom.py", line 20, in callback_connect
    self._join_room(room)
  File "/Users/sivy/envs/bot-py3/lib/python3.5/site-packages/errbot/core_plugins/chatRoom.py", line 34, in _join_room
    self.query_room(room).join(username=self.bot_config.CHATROOM_FN, password=password)
  File "/Users/sivy/envs/bot-py3/lib/python3.5/site-packages/errbot/backends/hipchat.py", line 166, in join
    if not self.exists:
  File "/Users/sivy/envs/bot-py3/lib/python3.5/site-packages/errbot/backends/hipchat.py", line 251, in exists
    self.hypchat.get_room(self.name)
  File "/Users/sivy/envs/bot-py3/lib/python3.5/site-packages/hypchat/__init__.py", line 151, in get_room
    return self.fromurl('{0}/v2/room/{1}'.format(self.endpoint, id_or_name), **kwargs)
  File "/Users/sivy/envs/bot-py3/lib/python3.5/site-packages/hypchat/__init__.py", line 115, in fromurl
    return Linker(url, _requests=self._requests)(**kwargs)
  File "/Users/sivy/envs/bot-py3/lib/python3.5/site-packages/hypchat/restobject.py", line 91, in __call__
    rv = self._obj_from_text(self._requests.get(self.url, params=params).text, self._requests)
  File "/Users/sivy/envs/bot-py3/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/Users/sivy/envs/bot-py3/lib/python3.5/site-packages/hypchat/__init__.py", line 58, in request
    resp = super(_requests, self).request(method, url, **kwargs)
  File "/Users/sivy/envs/bot-py3/lib/python3.5/site-packages/hypchat/requests.py", line 430, in request
    raise _http_errors[rv.status_code](rv.text, response=rv)
hypchat.requests.HttpUnauthorized: {
  "error": {
    "code": 401,
    "message": "Invalid OAuth session",
    "type": "Unauthorized"
  }
}
```

I'm using a v2 User token (from the Hipchat user profile screen), that looks like: `gVk4SY9C6JGibA7.....CyN0CuZX61iayOB3z67E`. I've also tried the v1 token (from the Hipchat server API admin screen) with no luck either. What am I missing? I get the same error when Errbot processes \@mentions. The room in this case is public, but the bot will need to be able to join private rooms as well.

Help?

**Comment by zoni** [comment] 2016-09-30 08:07
Does the token have all available oauth scopes applied?

**Comment by sivy** [comment] 2016-09-30 14:02
The token in question is from the User profile, and should have all the privileges of that user. I'm trying to get the bot to join an open room that it has ben added to as a member. I tried making the bot user an Admin, but it did not change the behavior.

**Comment by sivy** [comment] 2016-09-30 16:05
Atlassian HipChat v1.1.5 (2014.12.19.171429)

**Comment by zoni** [comment] 2016-10-02 15:37
> Atlassian HipChat v1.1.5 (2014.12.19.171429) 

That is a really old version. According to the [release notes](https://confluence.atlassian.com/hc/hipchat-server-release-notes-608731400.html) that is a beta version pre-dating the official release of HipChat Server.

Most likely that is why you are running into trouble.

I'm going to close this issue because of the above and the fact that I don't have access to HipChat server so I can't try to reproduce this either, however, if you have more information or continue to have this problem with a recent release of HipChat server then please don't hesitate to post it here and we'll see if there is anything more we may be able to do for you.

**Closed by zoni** 2016-10-02 15:37 UTC
