### ISSUE TITLE
DNS doesn't resolve for version.errbot.io

### ISSUE THREAD

**Issue by chadleeshaw** [errbotio/errbot#1375] opened 2019-08-19 16:36 UTC
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.1
* OS version: Centos 7
* Python version: 3.6.8
* Using a virtual environment: yes/(no)

### Issue description

VersionChecker is trying to reach the domain version.errbot.io which doesn't have a DNS entry
https://github.com/errbotio/errbot/blob/8c3d74995e316a14870527901ce89f2733691c53/errbot/core_plugins/vcheck.py#L11

Result of `dig version.errbot.io`

    ; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7_5.1 <<>> version.errbot.io
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 26827
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 4096
    ;; QUESTION SECTION:
    ;version.errbot.io.		IN	A

    ;; AUTHORITY SECTION:
    errbot.io.		280	IN	SOA	ns-cloud-e1.googledomains.com. cloud-dns- 
    hostmaster.google.com. 18 21600 3600 1209600 300

### Steps to reproduce

dig version.errbot.io

### Additional info

Note that I tried to just blacklist the VersionChecker (!plugin blacklist VersionChecker) however this produces an error:

    12:27:43 ERROR    errbot.plugin_manager     Error loading VersionChecker.
    Traceback (most recent call last):
        File "/usr/local/lib/python3.6/site-packages/errbot/plugin_manager.py", line 360, in 
        activate_non_started_plugins
        errors += f'Notice: {plugin.name} is blacklisted, ' \
    AttributeError: 'BotPluginManager' object has no attribute 'bot'

**Comment by sijis** [comment] 2019-08-19 17:22
Thank you for creating this. We've been aware of this problem for a few days now.

**Comment by fzipi** [comment] 2019-10-11 13:24
Well, keeps not working.

**Comment by griffinator76** [comment] 2019-10-25 00:40
Still not working..

**Comment by Imoq** [comment] 2019-12-27 11:53
Just adding a "me too" here, still not working.

`
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bot/proyecto/lib/python3.5/site-packages/errbot/core_plugins/vcheck.py", line 39, in _async_vcheck
    current_version_txt = requests.get(HOME, params={'errbot': VERSION, 'python': PY_VERSION}).text.strip()
  File "/home/bot/proyecto/lib/python3.5/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/bot/proyecto/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bot/proyecto/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bot/proyecto/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/bot/proyecto/lib/python3.5/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='version.errbot.io', port=80): Max retries exceeded with url: /?errbot=4.3.7&python=3.5.2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a335f6240>: Failed to establish a new connection: [Errno -2] Name or service not known',))
`

**Comment by sijis** [comment] 2019-12-28 17:32
This PR #1400 should address this by making it as part of the doc build process and not an external site.

**Comment by sijis** [comment] 2020-01-12 19:26
PR #1400 merged. It will be available upon next release. In the meantime, the fix is available when using the `master` branch.

**Closed by sijis** 2020-01-12 19:26 UTC
Labels: type: support/question
