### ISSUE TITLE
Plugin configuration fails: value [<type 'str'>] is not the same type as value [<type 'unicode'>]

### ISSUE THREAD

**Issue by cweiske** [errbotio/errbot#737] opened 2016-05-04 19:27 UTC
The configuration generated by the `--new-plugin` template requires extra work to play nicely with `!plugin config`:

    $ errbot --text
    ...
    !plugin config cfgtest {'str': 'Example value'}
    PluginConfigurationException: Example value [<type 'str'>] is not the same type as Example value [<type 'unicode'>]

Plugin code:

```
from errbot import BotPlugin, botcmd, arg_botcmd, webhook
class Cfgtest(BotPlugin):
    def get_configuration_template(self):
        return {'str': "Example value"}
```

When changing the template definition to `u"Example value"` it works:

    $ errbot --text
    ...
    !plugin config cfgtest {'str': 'Example value'}
    Plugin configuration done.

This is with errbot 4.0.3 on ubuntu 14.04, python 2.7

**Comment by gbin** [comment] 2016-05-09 18:15
I can't reproduce it in the test, did I miss something ?

**Comment by cweiske** [comment] 2016-05-09 18:52
is `exec_command` getting a unicode string when used in real?

**Comment by gbin** [comment] 2016-10-02 15:53
It is python2 only, on py3 we assume everything is unicode and the workaround is acceptable. I gonna close it

**Closed by gbin** 2016-10-02 15:53 UTC
Labels: #python2, priority: medium, type: bug
