### ISSUE TITLE
Errbot version 6.0.0+ fails to start because "Found more that one plugin for <class 'errbot.core.ErrBot'>"

### ISSUE THREAD

**Issue by tmcevoy14** [errbotio/errbot#1484] opened 2020-12-04 11:41 UTC
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.6
* OS version: CentOS 7.8.2003
* Python version: 3.6.8
* Using a virtual environment: yes

### Issue description

I'm trying to upgrade our errbot version from 5.2.0 to 6.1.6 and after upgrading to version 6.1.6 errbot fails to start because of this error:
`Found more that one plugin for <class 'errbot.core.ErrBot'>.
`

We are using errbot with the slack configuration and only have one backend defined. Any suggestions?

Our requirements.txt file looks like this:
```
pytz==2020.1           # (2020-04-20) - latest version
datadog==0.19.0        # (2018-06-04)
pyOpenSSL==17.5.0      # (2017-11-30)
errbot[slack]==6.1.6   # (2020-11-16) - latest version
slackclient==1.0.6     # (2017-08-02)
Markdown==3.3.3        # (2020-10-25) - latest version
pytest==3.7.1          # (2018-08-02)
paramiko==2.7.1        # (2019-12-09) - latest version
GitPython==2.1.11      # (2018-07-11)
black==20.8b1
```

We are using a custom slack backend that updates a few things for our use case:
`BACKEND = 'CustomSlack'`
`BOT_EXTRA_BACKEND_DIR = os.getenv('BACKENDS_PATH', '/srv/backends')`

And then our Custom Slack backend looks something like this (which is copied into `/srv/backends` when we build the image):
```
from plugins.libs.common import ui_blocks
from errbot.backends.base import Message
from errbot.backends.slack import (
    SlackBackend,
    SlackPerson,
    SlackRoomOccupant,
    SlackBot,
    SlackRoomBot,
    SlackRoom,
    SlackAPIResponseError,
)

log = logging.getLogger(__name__)


class CustomSlack(SlackBackend):
```

```
[Core]
Name = CustomSlack
Module = udemy_slack

[Python]
Version = 2+

[Documentation]
Description = Test stuff
```

### Steps to reproduce
Upgrade to 6.1.6 and run `errbot`

Upgrade to 
6.1.6 or 6.0.0

### Additional info
none

**Comment by tmcevoy14** [comment] 2021-01-07 14:38
Hi @sijis, can I get some support on this issue? It's blocking us from upgrading to version 6 of errbot and also upgrading our slackclient.

**Comment by nzlosh** [comment] 2021-01-07 14:43
What version of python are you using to run errbot 5.2.0?

**Comment by tmcevoy14** [comment] 2021-01-07 14:50
We're using python 3.6.8 to run errbot 5.2.0, and for the upgrade to errbot v6.

**Comment by nzlosh** [comment] 2021-01-07 15:09
I've encountered this error too. The error comes from the multiple inheritance:
`CustomSlack` > `SlackBackend` > `Errbot`

I workaround the issue by removing the multiple inheritance, but you in your case it this won't be useful.  My guess is this [PR](https://github.com/errbotio/errbot/pull/1347) may have change the behaviour of the import, but it's speculation.

**Comment by tmcevoy14** [comment] 2021-01-07 16:05
Looks like the cause of the issue - I wonder if it can be reverted or what the reasoning for it was?

**Comment by nzlosh** [comment] 2021-01-07 17:40
It will need to be confirmed as being the cause of the issue.  I'm not sure if it can be reverted now or a new patch will need to be devised.

**Comment by tmcevoy14** [comment] 2021-01-11 14:07
@sijis @gbin @attakei any idea if this could be fixed? Or if there's a workaround?

**Comment by sijis** [comment] 2021-01-12 06:34
@tmcevoy14 I haven't been able to look at this.hopefully it's something I can review in the next week.

Something that you can try is basically copying the slack backend into your custom one and try to remove a layer of inheritance. It's not perfect but it should allow you to validate other items to address in the migration.

**Comment by tmcevoy14** [comment] 2021-02-08 17:10
Hey @sijis, any update on this?

**Comment by sijis** [comment] 2021-02-12 05:49
Its possible you are hitting this bug https://github.com/errbotio/errbot/pull/1505.

**Comment by tmcevoy14** [comment] 2021-02-15 14:58
Thanks for the update @sijis, will that PR be merged soon?

**Comment by sijis** [comment] 2022-06-08 06:28
PR merged. should be in master.

**Closed by sijis** 2022-06-08 06:28 UTC
Labels: type: bug, backend: Common
