### ISSUE TITLE
Command & response translations/Internationalization

### ISSUE THREAD

**Issue by qlixed** [errbotio/errbot#946] opened 2017-01-19 23:09 UTC
### I am...

* [ ] Reporting a bug
* [X] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 4.3.5
* OS version: Fedora 25
* Python version: 3.5.2
* Using a virtual environment: yes

### Suggested Feature...
Could we make some kind of decorator that allow us to setup a command alias or translation?
In multi language environment can be useful if we can simplify add some kind of option to translate the command names.
Additionally could be useful the option of make the output of a command translatable based on the User or MUC preference.
Or maybe a initially simple approach that let us run multiple instances of the same bot in different languages. I think that this is not-so-hard(tm) to be done for the responses part, but still requires some work in the command name and params translations.

**Comment by andrewthetechie** [comment] 2019-01-05 05:33
Duplicate of https://github.com/errbotio/errbot/issues/648

#closeit

**Closed** 2019-01-05 17:07 UTC
